import * as fs from 'fs/promises';
import * as path from 'path';

export interface Decision {
  title: string;
  context: string;
  decision: string;
  consequences: string;
}

interface ADRResult {
  fileName: string;
  filePath: string;
}

/**
 * Generate the next sequential ADR number.
 */
async function getNextAdrNumber(adrDir: string): Promise<number> {
  let maxNum = 0;
  try {
    const entries = await fs.readdir(adrDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isFile()) {
        const match = entry.name.match(/^ADR-(\d+)/);
        if (match) {
          const num = parseInt(match[1], 10);
          if (num > maxNum) maxNum = num;
        }
      }
    }
  } catch {
    // Directory may not exist yet
  }
  return maxNum + 1;
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Write an Architecture Decision Record (ADR) to docs/adr/.
 */
export async function writeADR(projectRoot: string, decision: Decision): Promise<ADRResult> {
  const adrDir = path.join(projectRoot, 'docs', 'adr');
  await fs.mkdir(adrDir, { recursive: true });

  const num = await getNextAdrNumber(adrDir);
  const numStr = num.toString().padStart(3, '0');
  const slug = slugify(decision.title);
  const fileName = `ADR-${numStr}-${slug}.md`;
  const filePath = path.join(adrDir, fileName);

  const timestamp = new Date().toISOString();
  const content = `# ${fileName.replace('.md', '')}: ${decision.title}

**Date:** ${timestamp}
**Status:** Accepted

## Context

${decision.context}

## Decision

${decision.decision}

## Consequences

${decision.consequences}

---

*Auto-generated by Prism context monitor.*
`;

  await fs.writeFile(filePath, content, 'utf-8');
  return { fileName, filePath };
}
